import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Aladin } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const aladin = Aladin({
  weight: '400',
  subsets: ['latin'],
  display: "swap",
  variable: '--font-aladin'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${aladin.variable}`}>{children}</body>
    </html>
  )
}
